Add new tests and enhance build configuration
- Added a new dependency for the Xalan serializer in the pom.xml.
- Introduced a Maven dependency plugin to copy expected third-party jars during the package phase.
- Added an exec-maven-plugin to verify third-party dependencies after packaging.
- Updated runner.xml to simplify dependency inclusion and added exclusions for specific artifacts.
- Refactored the runBase script to improve Java environment detection.
- Created unit tests for NumberCompare, RandomUtils, TableFormater, TimeStopper, and StringUtils to ensure functionality and correctness.

diff --git a/jsystem-assembly/jsystem-runner/src/main/etc/runBase b/jsystem-assembly/jsystem-runner/src/main/etc/runBase
--- a/jsystem-assembly/jsystem-runner/src/main/etc/runBase
+++ b/jsystem-assembly/jsystem-runner/src/main/etc/runBase
@@ -13,17 +13,22 @@ PARAMS[6]=$@
 #===========================================================================
 setJavaEnvironment()
 {
-	_JAVACMD=java
-	if [ -f thirdparty/jdk/bin/java ]; then
-		_JAVACMD=thirdparty/jdk/bin/java
-		echo $_JAVACMD
-	elif [ -f ../jdk/bin/java ]; then
-		_JAVACMD=../jdk/bin/java
-		echo $_JAVACMD
-	elif [ -f $JAVA_HOME/bin/java ]; then
-		_JAVACMD=$JAVA_HOME/bin/java
-		echo $_JAVACMD
+	_JAVACMD=$(readlink -f $(which java))
+	if [ "X$_JAVACMD" == "X" ]; then
+		echo "java command not found, please make sure java is installed and added to the PATH variable."
+		exit 1
 	fi
+	JAVA_HOME=$(dirname $(dirname $_JAVACMD))
+#	if [ -f thirdparty/jdk/bin/java ]; then
+#		_JAVACMD=thirdparty/jdk/bin/java
+#		echo $_JAVACMD
+#	elif [ -f ../jdk/bin/java ]; then
+#		_JAVACMD=../jdk/bin/java
+#		echo $_JAVACMD
+#	elif [ -f $JAVA_HOME/bin/java ]; then
+#		_JAVACMD=$JAVA_HOME/bin/java
+#		echo $_JAVACMD
+#	fi
 }
 
 launch(){
